load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "constexpr_map",
    hdrs = ["constexpr_map.h"],
    deps = [
        "//third_party/mapbox/eternal",
    ],
)
